# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  codecov: codecov/codecov@1.2.3
jobs:
  build:
    working_directory: ~/qrcode
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -race -coverprofile=/tmp/coverage.txt -covermode=atomic
      - codecov/upload:
          file: '/tmp/coverage.txt'
          token: f54774de-aedd-4e47-b63b-f51bc2fb8574
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
